server:
  port: 8888
spring:
  profiles:
    active: dev
---
server:
  port: 8889
spring:
  profiles: dev

---
server:
  port: 8890
spring:
  profiles: prod

#person:
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,k2: v2}
#  lists:
#    - list
#    - 赵六
#  dog:
#    name: 小狗
#    age: 2